### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kotmatross28729** [calreveraster/OptiFix#1]

**Comment by calreveraster** [comment]
Honestly didnt even see this until you closed it, but this is actually the main thing I'm planning on fixing. I know exactly the code block that breaks and have a working version of a fix, but need to make it comply with licensing/etc 

Once I have that figured out it's going to be loaded up here

**Comment by kotmatross28729** [comment]
My friend already found a solution, the [Blendtronic](https://github.com/GTMEGA/Blendtronic) mod seems to fix the problem. If I'm not mistaken, this is https://github.com/GTMEGA/Blendtronic/blob/main/src/main/java/mega/blendtronic/modules/optifine/ShaderMappingFix.java
